# The provided setup is for development purposes only. It is intentionally
# kept very simple and would not be used this way in production.
services:

  dev:
    build: .
    env_file:
      - .env
    environment:
      - VITE_BACKEND_PORT=${BACKEND_PORT}
      - VITE_CODESPACE_NAME=${CODESPACE_NAME}
      - WATCHFILES_FORCE_POLLING=true
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    working_dir: /app
    volumes:
      - .:/app
      - /app/frontend/node_modules
    command: ./run_dev.sh

  db:
    image: postgres:16.3
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    command: -p ${POSTGRES_PORT}

volumes:
  postgres-data:
